//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Takamul.Portal.Resources.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Takamul.Portal.Resources.Common.CommonResx", typeof(CommonResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied.
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessibility.
        /// </summary>
        public static string Accessibility {
            get {
                return ResourceManager.GetString("Accessibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! Access Denied, you do not have sufficient privileges..
        /// </summary>
        public static string AccessisDenied {
            get {
                return ResourceManager.GetString("AccessisDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Company User.
        /// </summary>
        public static string AddCompanyUser {
            get {
                return ResourceManager.GetString("AddCompanyUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Search.
        /// </summary>
        public static string AdvancedSearch {
            get {
                return ResourceManager.GetString("AdvancedSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Applications.
        /// </summary>
        public static string AllApplications {
            get {
                return ResourceManager.GetString("AllApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Departments.
        /// </summary>
        public static string AllDepartments {
            get {
                return ResourceManager.GetString("AllDepartments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Directorates.
        /// </summary>
        public static string AllDirectorates {
            get {
                return ResourceManager.GetString("AllDirectorates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Members.
        /// </summary>
        public static string AllMembers {
            get {
                return ResourceManager.GetString("AllMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Sections.
        /// </summary>
        public static string AllSections {
            get {
                return ResourceManager.GetString("AllSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Sectors.
        /// </summary>
        public static string AllSectors {
            get {
                return ResourceManager.GetString("AllSectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Almost Expired.
        /// </summary>
        public static string AlmostExpired {
            get {
                return ResourceManager.GetString("AlmostExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The section you are trying to add is already exist, please try with a different one..
        /// </summary>
        public static string AlreadyExistRecordFaild {
            get {
                return ResourceManager.GetString("AlreadyExistRecordFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has been occurred please try again later.
        /// </summary>
        public static string AnErrorHasBeenOccured {
            get {
                return ResourceManager.GetString("AnErrorHasBeenOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App DashBoard.
        /// </summary>
        public static string AppDashBoard {
            get {
                return ResourceManager.GetString("AppDashBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Events.
        /// </summary>
        public static string AppEvents {
            get {
                return ResourceManager.GetString("AppEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Info.
        /// </summary>
        public static string AppInfo {
            get {
                return ResourceManager.GetString("AppInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Member Info.
        /// </summary>
        public static string AppMemberInfo {
            get {
                return ResourceManager.GetString("AppMemberInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Name.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App News.
        /// </summary>
        public static string AppNews {
            get {
                return ResourceManager.GetString("AppNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Settings.
        /// </summary>
        public static string AppSettings {
            get {
                return ResourceManager.GetString("AppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Tickets.
        /// </summary>
        public static string AppTickets {
            get {
                return ResourceManager.GetString("AppTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Users.
        /// </summary>
        public static string AppUsers {
            get {
                return ResourceManager.GetString("AppUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back To List.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth date.
        /// </summary>
        public static string Birthdate {
            get {
                return ResourceManager.GetString("Birthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no-skin.
        /// </summary>
        public static string BodyClass {
            get {
                return ResourceManager.GetString("BodyClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        public static string Branch {
            get {
                return ResourceManager.GetString("Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Center.
        /// </summary>
        public static string CallCenter {
            get {
                return ResourceManager.GetString("CallCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t insert in this date because its before the submission date..
        /// </summary>
        public static string CanNotInsertInThisDate {
            get {
                return ResourceManager.GetString("CanNotInsertInThisDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t delete this event log, becuase this is not done by you and/or this is not a custom event..
        /// </summary>
        public static string CantDeleteThisEventType {
            get {
                return ResourceManager.GetString("CantDeleteThisEventType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the string as shown above:.
        /// </summary>
        public static string CaptchaText {
            get {
                return ResourceManager.GetString("CaptchaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Characters left.
        /// </summary>
        public static string CharactersLeft {
            get {
                return ResourceManager.GetString("CharactersLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citizens.
        /// </summary>
        public static string CitizensEServicesPortal {
            get {
                return ResourceManager.GetString("CitizensEServicesPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civil Number.
        /// </summary>
        public static string CivilNumber {
            get {
                return ResourceManager.GetString("CivilNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company changed successfully.
        /// </summary>
        public static string CompanyChangedSuccessfully {
            get {
                return ResourceManager.GetString("CompanyChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company changing error, please try again later.
        /// </summary>
        public static string CompanyNotChanged {
            get {
                return ResourceManager.GetString("CompanyNotChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to padding-right:3em;.
        /// </summary>
        public static string ComplaintDetailsMapsStyle {
            get {
                return ResourceManager.GetString("ComplaintDetailsMapsStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your complaints has been submitted successfully , You can follow up by using the reference number.
        /// </summary>
        public static string ComplaintRefNo {
            get {
                return ResourceManager.GetString("ComplaintRefNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact US.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show content.
        /// </summary>
        public static string ContentViewer {
            get {
                return ResourceManager.GetString("ContentViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © {0} Ministry of Manpower – Sultanate of Oman. All Rights Reserved..
        /// </summary>
        public static string CopyRight {
            get {
                return ResourceManager.GetString("CopyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Court.
        /// </summary>
        public static string Court {
            get {
                return ResourceManager.GetString("Court", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comercial Record Number.
        /// </summary>
        public static string CrNumber {
            get {
                return ResourceManager.GetString("CrNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Company : {0}.
        /// </summary>
        public static string CurrentSelectedComany {
            get {
                return ResourceManager.GetString("CurrentSelectedComany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wanted to delete this record ?.
        /// </summary>
        public static string DeleteConfirmationMessage {
            get {
                return ResourceManager.GetString("DeleteConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure.
        /// </summary>
        public static string Departure {
            get {
                return ResourceManager.GetString("Departure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Described as.
        /// </summary>
        public static string Described {
            get {
                return ResourceManager.GetString("Described", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ltr.
        /// </summary>
        public static string dir {
            get {
                return ResourceManager.GetString("dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ltr.
        /// </summary>
        public static string Direction {
            get {
                return ResourceManager.GetString("Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rtl.
        /// </summary>
        public static string DirectionOpposite {
            get {
                return ResourceManager.GetString("DirectionOpposite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directorate.
        /// </summary>
        public static string Directorate {
            get {
                return ResourceManager.GetString("Directorate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ace-icon fa fa-angle-double-right.
        /// </summary>
        public static string DoubleArrowIcon {
            get {
                return ResourceManager.GetString("DoubleArrowIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ace-icon fa fa-angle-double-left.
        /// </summary>
        public static string DoubleArrowIconMenu {
            get {
                return ResourceManager.GetString("DoubleArrowIconMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ministry Employee.
        /// </summary>
        public static string EmployeeEServicesPortal {
            get {
                return ResourceManager.GetString("EmployeeEServicesPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employers.
        /// </summary>
        public static string EmployerEServicesPortal {
            get {
                return ResourceManager.GetString("EmployerEServicesPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error Occurred.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorPage {
            get {
                return ResourceManager.GetString("ErrorPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eServices.
        /// </summary>
        public static string EServices {
            get {
                return ResourceManager.GetString("EServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired.
        /// </summary>
        public static string Expired {
            get {
                return ResourceManager.GetString("Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        public static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date.
        /// </summary>
        public static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Error.
        /// </summary>
        public static string GeneralError {
            get {
                return ResourceManager.GetString("GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Back To All Application.
        /// </summary>
        public static string GoBackToAllApplication {
            get {
                return ResourceManager.GetString("GoBackToAllApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here.
        /// </summary>
        public static string Here {
            get {
                return ResourceManager.GetString("Here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $(&quot;.ui-inline-del&quot;).hide();.
        /// </summary>
        public static string HideInLineDelete {
            get {
                return ResourceManager.GetString("HideInLineDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $(&quot;.ui-inline-edit&quot;).hide();.
        /// </summary>
        public static string HideInLineEdit {
            get {
                return ResourceManager.GetString("HideInLineEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress ....
        /// </summary>
        public static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Seeker.
        /// </summary>
        public static string JobSeekerEServicesPortal {
            get {
                return ResourceManager.GetString("JobSeekerEServicesPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left.
        /// </summary>
        public static string LayoutDirection {
            get {
                return ResourceManager.GetString("LayoutDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to right.
        /// </summary>
        public static string LayoutDirectionOpposite {
            get {
                return ResourceManager.GetString("LayoutDirectionOpposite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/assets/images/logo_en.png.
        /// </summary>
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eServices .
        /// </summary>
        public static string MainTitle {
            get {
                return ResourceManager.GetString("MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manpower.
        /// </summary>
        public static string ManpowerEServicesPortal {
            get {
                return ResourceManager.GetString("ManpowerEServicesPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add failed.
        /// </summary>
        public static string MessageAddFailed {
            get {
                return ResourceManager.GetString("MessageAddFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record(s) has been added successfully.
        /// </summary>
        public static string MessageAddSuccess {
            get {
                return ResourceManager.GetString("MessageAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Assigning the Question.
        /// </summary>
        public static string MessageAssignFaild {
            get {
                return ResourceManager.GetString("MessageAssignFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Question has been Assigned Successfully.
        /// </summary>
        public static string MessageAssignSuccess {
            get {
                return ResourceManager.GetString("MessageAssignSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete failed.
        /// </summary>
        public static string MessageDeleteFailed {
            get {
                return ResourceManager.GetString("MessageDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record(s) has been deleted successfully.
        /// </summary>
        public static string MessageDeleteSuccess {
            get {
                return ResourceManager.GetString("MessageDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit failed.
        /// </summary>
        public static string MessageEditFailed {
            get {
                return ResourceManager.GetString("MessageEditFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record(s) has been edited successfully.
        /// </summary>
        public static string MessageEditSuccess {
            get {
                return ResourceManager.GetString("MessageEditSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ministerial Decrees.
        /// </summary>
        public static string MinisterialDecrees {
            get {
                return ResourceManager.GetString("MinisterialDecrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ministry of Manpower.
        /// </summary>
        public static string MinistryOfManpower {
            get {
                return ResourceManager.GetString("MinistryOfManpower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Applications.
        /// </summary>
        public static string MobileApplication {
            get {
                return ResourceManager.GetString("MobileApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Application.
        /// </summary>
        public static string MyApplication {
            get {
                return ResourceManager.GetString("MyApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data releated to this selection  ..
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data Found.
        /// </summary>
        public static string NoDataFound {
            get {
                return ResourceManager.GetString("NoDataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No selected records.
        /// </summary>
        public static string NoSelectedRecords {
            get {
                return ResourceManager.GetString("NoSelectedRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Available.
        /// </summary>
        public static string NotAvailable {
            get {
                return ResourceManager.GetString("NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Exist.
        /// </summary>
        public static string NotExist {
            get {
                return ResourceManager.GetString("NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has been occured through payment proccess please try again later.
        /// </summary>
        public static string PaymentError {
            get {
                return ResourceManager.GetString("PaymentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Validation Error.
        /// </summary>
        public static string PaymentValidationError {
            get {
                return ResourceManager.GetString("PaymentValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Called Mr..
        /// </summary>
        public static string PhoneCall {
            get {
                return ResourceManager.GetString("PhoneCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Age.
        /// </summary>
        public static string PleaseEnterAge {
            get {
                return ResourceManager.GetString("PleaseEnterAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select.
        /// </summary>
        public static string PleaseSelect {
            get {
                return ResourceManager.GetString("PleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to padding-right:2em; padding-left: 0em;.
        /// </summary>
        public static string ProclamationAttachmentsStyle {
            get {
                return ResourceManager.GetString("ProclamationAttachmentsStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to padding-right:2em;padding-left: 0em;.
        /// </summary>
        public static string ProclamationDetailsMapsStyle {
            get {
                return ResourceManager.GetString("ProclamationDetailsMapsStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Code.
        /// </summary>
        public static string REFCode {
            get {
                return ResourceManager.GetString("REFCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regulations.
        /// </summary>
        public static string Regulations {
            get {
                return ResourceManager.GetString("Regulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cant delete this record(s), please delete childe record(s) before this action..
        /// </summary>
        public static string RelatedRecordFaild {
            get {
                return ResourceManager.GetString("RelatedRecordFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 900.
        /// </summary>
        public static string ReportViewerHeight {
            get {
                return ResourceManager.GetString("ReportViewerHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 600.
        /// </summary>
        public static string ReportViewerHeightWide {
            get {
                return ResourceManager.GetString("ReportViewerHeightWide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 770.
        /// </summary>
        public static string ReportViewerWidth {
            get {
                return ResourceManager.GetString("ReportViewerWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1130.
        /// </summary>
        public static string ReportViewerWidthWide {
            get {
                return ResourceManager.GetString("ReportViewerWidthWide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Field.
        /// </summary>
        public static string RequiredInputNote {
            get {
                return ResourceManager.GetString("RequiredInputNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runaway.
        /// </summary>
        public static string Runaway {
            get {
                return ResourceManager.GetString("Runaway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAWA eService Login.
        /// </summary>
        public static string SAWAeServiceLogin {
            get {
                return ResourceManager.GetString("SAWAeServiceLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        public static string Section {
            get {
                return ResourceManager.GetString("Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector.
        /// </summary>
        public static string Sector {
            get {
                return ResourceManager.GetString("Sector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Company.
        /// </summary>
        public static string SelectCompany {
            get {
                return ResourceManager.GetString("SelectCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Department.
        /// </summary>
        public static string SelectDepartment {
            get {
                return ResourceManager.GetString("SelectDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Directorate.
        /// </summary>
        public static string SelectDirectorate {
            get {
                return ResourceManager.GetString("SelectDirectorate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Section.
        /// </summary>
        public static string SelectSection {
            get {
                return ResourceManager.GetString("SelectSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Sector.
        /// </summary>
        public static string SelectSector {
            get {
                return ResourceManager.GetString("SelectSector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Not Available.
        /// </summary>
        public static string ServiceNotAvailable {
            get {
                return ResourceManager.GetString("ServiceNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All Services.
        /// </summary>
        public static string ShowAllServices {
            get {
                return ResourceManager.GetString("ShowAllServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Report.
        /// </summary>
        public static string ShowReport {
            get {
                return ResourceManager.GetString("ShowReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Map.
        /// </summary>
        public static string SiteMap {
            get {
                return ResourceManager.GetString("SiteMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portal Eservices - Ministry of Manpower Sultanate of Oman.
        /// </summary>
        public static string SiteTitle {
            get {
                return ResourceManager.GetString("SiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Mail.
        /// </summary>
        public static string StaffMail {
            get {
                return ResourceManager.GetString("StaffMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        public static string Star {
            get {
                return ResourceManager.GetString("Star", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAWA eServices.
        /// </summary>
        public static string TakamulServices {
            get {
                return ResourceManager.GetString("TakamulServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms &amp; Conditions.
        /// </summary>
        public static string TermsAndConditions {
            get {
                return ResourceManager.GetString("TermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left.
        /// </summary>
        public static string TextAlign {
            get {
                return ResourceManager.GetString("TextAlign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required..
        /// </summary>
        public static string ThisFieldIsRequired {
            get {
                return ResourceManager.GetString("ThisFieldIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Here to Change.
        /// </summary>
        public static string ToChangeCompany {
            get {
                return ResourceManager.GetString("ToChangeCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date.
        /// </summary>
        public static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Institute.
        /// </summary>
        public static string TrainingInstitutePortal {
            get {
                return ResourceManager.GetString("TrainingInstitutePortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined.
        /// </summary>
        public static string Undefined {
            get {
                return ResourceManager.GetString("Undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User assigned to company successfully.
        /// </summary>
        public static string UserCompanyAssignSuccess {
            get {
                return ResourceManager.GetString("UserCompanyAssignSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use System as .
        /// </summary>
        public static string UseSystemAsCompany {
            get {
                return ResourceManager.GetString("UseSystemAsCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will Expire Soon.
        /// </summary>
        public static string WillExpireSoon {
            get {
                return ResourceManager.GetString("WillExpireSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working.
        /// </summary>
        public static string Working {
            get {
                return ResourceManager.GetString("Working", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Law.
        /// </summary>
        public static string WorkLaw {
            get {
                return ResourceManager.GetString("WorkLaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
