//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Takamul.Portal.Resources.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommonResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Takamul.Portal.Resources.Common.CommonResx", typeof(CommonResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessibility.
        /// </summary>
        internal static string Accessibility {
            get {
                return ResourceManager.GetString("Accessibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! Access Denied, you do not have sufficient privileges..
        /// </summary>
        internal static string AccessisDenied {
            get {
                return ResourceManager.GetString("AccessisDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Company User.
        /// </summary>
        internal static string AddCompanyUser {
            get {
                return ResourceManager.GetString("AddCompanyUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Search.
        /// </summary>
        internal static string AdvancedSearch {
            get {
                return ResourceManager.GetString("AdvancedSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Departments.
        /// </summary>
        internal static string AllDepartments {
            get {
                return ResourceManager.GetString("AllDepartments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Directorates.
        /// </summary>
        internal static string AllDirectorates {
            get {
                return ResourceManager.GetString("AllDirectorates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Sections.
        /// </summary>
        internal static string AllSections {
            get {
                return ResourceManager.GetString("AllSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Sectors.
        /// </summary>
        internal static string AllSectors {
            get {
                return ResourceManager.GetString("AllSectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Almost Expired.
        /// </summary>
        internal static string AlmostExpired {
            get {
                return ResourceManager.GetString("AlmostExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The section you are trying to add is already exist, please try with a different one..
        /// </summary>
        internal static string AlreadyExistRecordFaild {
            get {
                return ResourceManager.GetString("AlreadyExistRecordFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has been occurred please try again later.
        /// </summary>
        internal static string AnErrorHasBeenOccured {
            get {
                return ResourceManager.GetString("AnErrorHasBeenOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        internal static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth date.
        /// </summary>
        internal static string Birthdate {
            get {
                return ResourceManager.GetString("Birthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no-skin.
        /// </summary>
        internal static string BodyClass {
            get {
                return ResourceManager.GetString("BodyClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        internal static string Branch {
            get {
                return ResourceManager.GetString("Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Center.
        /// </summary>
        internal static string CallCenter {
            get {
                return ResourceManager.GetString("CallCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        internal static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t insert in this date because its before the submission date..
        /// </summary>
        internal static string CanNotInsertInThisDate {
            get {
                return ResourceManager.GetString("CanNotInsertInThisDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t delete this event log, becuase this is not done by you and/or this is not a custom event..
        /// </summary>
        internal static string CantDeleteThisEventType {
            get {
                return ResourceManager.GetString("CantDeleteThisEventType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the string as shown above:.
        /// </summary>
        internal static string CaptchaText {
            get {
                return ResourceManager.GetString("CaptchaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Characters left.
        /// </summary>
        internal static string CharactersLeft {
            get {
                return ResourceManager.GetString("CharactersLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citizens.
        /// </summary>
        internal static string CitizensEServicesPortal {
            get {
                return ResourceManager.GetString("CitizensEServicesPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civil Number.
        /// </summary>
        internal static string CivilNumber {
            get {
                return ResourceManager.GetString("CivilNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company changed successfully.
        /// </summary>
        internal static string CompanyChangedSuccessfully {
            get {
                return ResourceManager.GetString("CompanyChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company changing error, please try again later.
        /// </summary>
        internal static string CompanyNotChanged {
            get {
                return ResourceManager.GetString("CompanyNotChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to padding-right:3em;.
        /// </summary>
        internal static string ComplaintDetailsMapsStyle {
            get {
                return ResourceManager.GetString("ComplaintDetailsMapsStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your complaints has been submitted successfully , You can follow up by using the reference number.
        /// </summary>
        internal static string ComplaintRefNo {
            get {
                return ResourceManager.GetString("ComplaintRefNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact US.
        /// </summary>
        internal static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show content.
        /// </summary>
        internal static string ContentViewer {
            get {
                return ResourceManager.GetString("ContentViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © {0} Ministry of Manpower – Sultanate of Oman. All Rights Reserved..
        /// </summary>
        internal static string CopyRight {
            get {
                return ResourceManager.GetString("CopyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Court.
        /// </summary>
        internal static string Court {
            get {
                return ResourceManager.GetString("Court", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comercial Record Number.
        /// </summary>
        internal static string CrNumber {
            get {
                return ResourceManager.GetString("CrNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Company : {0}.
        /// </summary>
        internal static string CurrentSelectedComany {
            get {
                return ResourceManager.GetString("CurrentSelectedComany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure.
        /// </summary>
        internal static string Departure {
            get {
                return ResourceManager.GetString("Departure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Described as.
        /// </summary>
        internal static string Described {
            get {
                return ResourceManager.GetString("Described", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ltr.
        /// </summary>
        internal static string dir {
            get {
                return ResourceManager.GetString("dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ltr.
        /// </summary>
        internal static string Direction {
            get {
                return ResourceManager.GetString("Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rtl.
        /// </summary>
        internal static string DirectionOpposite {
            get {
                return ResourceManager.GetString("DirectionOpposite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directorate.
        /// </summary>
        internal static string Directorate {
            get {
                return ResourceManager.GetString("Directorate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ace-icon fa fa-angle-double-right.
        /// </summary>
        internal static string DoubleArrowIcon {
            get {
                return ResourceManager.GetString("DoubleArrowIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ace-icon fa fa-angle-double-left.
        /// </summary>
        internal static string DoubleArrowIconMenu {
            get {
                return ResourceManager.GetString("DoubleArrowIconMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ministry Employee.
        /// </summary>
        internal static string EmployeeEServicesPortal {
            get {
                return ResourceManager.GetString("EmployeeEServicesPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employers.
        /// </summary>
        internal static string EmployerEServicesPortal {
            get {
                return ResourceManager.GetString("EmployerEServicesPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error Occurred.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eServices.
        /// </summary>
        internal static string EServices {
            get {
                return ResourceManager.GetString("EServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired.
        /// </summary>
        internal static string Expired {
            get {
                return ResourceManager.GetString("Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        internal static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date.
        /// </summary>
        internal static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Error.
        /// </summary>
        internal static string GeneralError {
            get {
                return ResourceManager.GetString("GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here.
        /// </summary>
        internal static string Here {
            get {
                return ResourceManager.GetString("Here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $(&quot;.ui-inline-del&quot;).hide();.
        /// </summary>
        internal static string HideInLineDelete {
            get {
                return ResourceManager.GetString("HideInLineDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $(&quot;.ui-inline-edit&quot;).hide();.
        /// </summary>
        internal static string HideInLineEdit {
            get {
                return ResourceManager.GetString("HideInLineEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress ....
        /// </summary>
        internal static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Seeker.
        /// </summary>
        internal static string JobSeekerEServicesPortal {
            get {
                return ResourceManager.GetString("JobSeekerEServicesPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left.
        /// </summary>
        internal static string LayoutDirection {
            get {
                return ResourceManager.GetString("LayoutDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to right.
        /// </summary>
        internal static string LayoutDirectionOpposite {
            get {
                return ResourceManager.GetString("LayoutDirectionOpposite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/assets/images/logo_en.png.
        /// </summary>
        internal static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eServices .
        /// </summary>
        internal static string MainTitle {
            get {
                return ResourceManager.GetString("MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manpower.
        /// </summary>
        internal static string ManpowerEServicesPortal {
            get {
                return ResourceManager.GetString("ManpowerEServicesPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add failed.
        /// </summary>
        internal static string MessageAddFailed {
            get {
                return ResourceManager.GetString("MessageAddFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record(s) has been added successfully.
        /// </summary>
        internal static string MessageAddSuccess {
            get {
                return ResourceManager.GetString("MessageAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Assigning the Question.
        /// </summary>
        internal static string MessageAssignFaild {
            get {
                return ResourceManager.GetString("MessageAssignFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Question has been Assigned Successfully.
        /// </summary>
        internal static string MessageAssignSuccess {
            get {
                return ResourceManager.GetString("MessageAssignSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete failed.
        /// </summary>
        internal static string MessageDeleteFailed {
            get {
                return ResourceManager.GetString("MessageDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record(s) has been deleted successfully.
        /// </summary>
        internal static string MessageDeleteSuccess {
            get {
                return ResourceManager.GetString("MessageDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit failed.
        /// </summary>
        internal static string MessageEditFailed {
            get {
                return ResourceManager.GetString("MessageEditFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record(s) has been edited successfully.
        /// </summary>
        internal static string MessageEditSuccess {
            get {
                return ResourceManager.GetString("MessageEditSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ministerial Decrees.
        /// </summary>
        internal static string MinisterialDecrees {
            get {
                return ResourceManager.GetString("MinisterialDecrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ministry of Manpower.
        /// </summary>
        internal static string MinistryOfManpower {
            get {
                return ResourceManager.GetString("MinistryOfManpower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Applications.
        /// </summary>
        internal static string MobileApplication {
            get {
                return ResourceManager.GetString("MobileApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data releated to this selection  ..
        /// </summary>
        internal static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data Found.
        /// </summary>
        internal static string NoDataFound {
            get {
                return ResourceManager.GetString("NoDataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No selected records.
        /// </summary>
        internal static string NoSelectedRecords {
            get {
                return ResourceManager.GetString("NoSelectedRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Available.
        /// </summary>
        internal static string NotAvailable {
            get {
                return ResourceManager.GetString("NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Exist.
        /// </summary>
        internal static string NotExist {
            get {
                return ResourceManager.GetString("NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has been occured through payment proccess please try again later.
        /// </summary>
        internal static string PaymentError {
            get {
                return ResourceManager.GetString("PaymentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Validation Error.
        /// </summary>
        internal static string PaymentValidationError {
            get {
                return ResourceManager.GetString("PaymentValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        internal static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Called Mr..
        /// </summary>
        internal static string PhoneCall {
            get {
                return ResourceManager.GetString("PhoneCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Age.
        /// </summary>
        internal static string PleaseEnterAge {
            get {
                return ResourceManager.GetString("PleaseEnterAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select.
        /// </summary>
        internal static string PleaseSelect {
            get {
                return ResourceManager.GetString("PleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        internal static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to padding-right:2em; padding-left: 0em;.
        /// </summary>
        internal static string ProclamationAttachmentsStyle {
            get {
                return ResourceManager.GetString("ProclamationAttachmentsStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to padding-right:2em;padding-left: 0em;.
        /// </summary>
        internal static string ProclamationDetailsMapsStyle {
            get {
                return ResourceManager.GetString("ProclamationDetailsMapsStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Code.
        /// </summary>
        internal static string REFCode {
            get {
                return ResourceManager.GetString("REFCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regulations.
        /// </summary>
        internal static string Regulations {
            get {
                return ResourceManager.GetString("Regulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cant delete this record(s), please delete childe record(s) before this action..
        /// </summary>
        internal static string RelatedRecordFaild {
            get {
                return ResourceManager.GetString("RelatedRecordFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 900.
        /// </summary>
        internal static string ReportViewerHeight {
            get {
                return ResourceManager.GetString("ReportViewerHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 600.
        /// </summary>
        internal static string ReportViewerHeightWide {
            get {
                return ResourceManager.GetString("ReportViewerHeightWide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 770.
        /// </summary>
        internal static string ReportViewerWidth {
            get {
                return ResourceManager.GetString("ReportViewerWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1130.
        /// </summary>
        internal static string ReportViewerWidthWide {
            get {
                return ResourceManager.GetString("ReportViewerWidthWide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Field.
        /// </summary>
        internal static string RequiredInputNote {
            get {
                return ResourceManager.GetString("RequiredInputNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        internal static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runaway.
        /// </summary>
        internal static string Runaway {
            get {
                return ResourceManager.GetString("Runaway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        internal static string Section {
            get {
                return ResourceManager.GetString("Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector.
        /// </summary>
        internal static string Sector {
            get {
                return ResourceManager.GetString("Sector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Company.
        /// </summary>
        internal static string SelectCompany {
            get {
                return ResourceManager.GetString("SelectCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Department.
        /// </summary>
        internal static string SelectDepartment {
            get {
                return ResourceManager.GetString("SelectDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Directorate.
        /// </summary>
        internal static string SelectDirectorate {
            get {
                return ResourceManager.GetString("SelectDirectorate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Section.
        /// </summary>
        internal static string SelectSection {
            get {
                return ResourceManager.GetString("SelectSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Sector.
        /// </summary>
        internal static string SelectSector {
            get {
                return ResourceManager.GetString("SelectSector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Not Available.
        /// </summary>
        internal static string ServiceNotAvailable {
            get {
                return ResourceManager.GetString("ServiceNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All Services.
        /// </summary>
        internal static string ShowAllServices {
            get {
                return ResourceManager.GetString("ShowAllServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Report.
        /// </summary>
        internal static string ShowReport {
            get {
                return ResourceManager.GetString("ShowReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Map.
        /// </summary>
        internal static string SiteMap {
            get {
                return ResourceManager.GetString("SiteMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portal Eservices - Ministry of Manpower Sultanate of Oman.
        /// </summary>
        internal static string SiteTitle {
            get {
                return ResourceManager.GetString("SiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Mail.
        /// </summary>
        internal static string StaffMail {
            get {
                return ResourceManager.GetString("StaffMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string Star {
            get {
                return ResourceManager.GetString("Star", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms &amp; Conditions.
        /// </summary>
        internal static string TermsAndConditions {
            get {
                return ResourceManager.GetString("TermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left.
        /// </summary>
        internal static string TextAlign {
            get {
                return ResourceManager.GetString("TextAlign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Here to Change.
        /// </summary>
        internal static string ToChangeCompany {
            get {
                return ResourceManager.GetString("ToChangeCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date.
        /// </summary>
        internal static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Institute.
        /// </summary>
        internal static string TrainingInstitutePortal {
            get {
                return ResourceManager.GetString("TrainingInstitutePortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined.
        /// </summary>
        internal static string Undefined {
            get {
                return ResourceManager.GetString("Undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User assigned to company successfully.
        /// </summary>
        internal static string UserCompanyAssignSuccess {
            get {
                return ResourceManager.GetString("UserCompanyAssignSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use System as .
        /// </summary>
        internal static string UseSystemAsCompany {
            get {
                return ResourceManager.GetString("UseSystemAsCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will Expire Soon.
        /// </summary>
        internal static string WillExpireSoon {
            get {
                return ResourceManager.GetString("WillExpireSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working.
        /// </summary>
        internal static string Working {
            get {
                return ResourceManager.GetString("Working", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Law.
        /// </summary>
        internal static string WorkLaw {
            get {
                return ResourceManager.GetString("WorkLaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
