//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Takamul.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ABOUTAPP_LINKS
    {
        public int ID { get; set; }
        public string Howitworks { get; set; }
        public string InstallationInstruction { get; set; }
        public string FAQ { get; set; }
        public string AppGuide { get; set; }
        public string Privacyandpolicies { get; set; }
        public string Termsandcondition { get; set; }
        public string InformationSecurity { get; set; }
    }
}
