//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Takamul.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPLICATION_ENTITIES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public APPLICATION_ENTITIES()
        {
            this.APPLICATION_PRIVILLAGES = new HashSet<APPLICATION_PRIVILLAGES>();
        }
    
        public int ID { get; set; }
        public string ENTITY_NAME { get; set; }
        public string ENTITY_CONTROLLER { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APPLICATION_PRIVILLAGES> APPLICATION_PRIVILLAGES { get; set; }
    }
}
