//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Takamul.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TakamulConnection : DbContext
    {
        public TakamulConnection()
            : base("name=TakamulConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<APPLICATIONS> APPLICATIONS { get; set; }
        public virtual DbSet<MEMBER_INFO> MEMBER_INFO { get; set; }
        public virtual DbSet<NEWS> NEWS { get; set; }
        public virtual DbSet<APPLICATION_INFO> APPLICATION_INFO { get; set; }
        public virtual DbSet<APPLICATION_MASTER_SETTINGS> APPLICATION_MASTER_SETTINGS { get; set; }
        public virtual DbSet<APPLICATION_SETTINGS> APPLICATION_SETTINGS { get; set; }
        public virtual DbSet<EVENTS> EVENTS { get; set; }
        public virtual DbSet<APPLICATION_CATEGORIES> APPLICATION_CATEGORIES { get; set; }
    }
}
