//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Takamul.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TICKET_CHAT_DETAILS
    {
        public int ID { get; set; }
        public int TICKET_ID { get; set; }
        public string REPLY_MESSAGE { get; set; }
        public Nullable<System.DateTime> REPLIED_DATE { get; set; }
        public string REPLY_FILE_PATH { get; set; }
        public Nullable<int> TICKET_PARTICIPANT_ID { get; set; }
        public Nullable<int> TICKET_CHAT_TYPE_ID { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
    
        public virtual TICKETS TICKETS { get; set; }
    }
}
