//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Takamul.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_DETAILS
    {
        public int ID { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public string FULL_NAME { get; set; }
        public string CIVIL_ID { get; set; }
        public string ADDRESS { get; set; }
        public Nullable<int> AREA_ID { get; set; }
        public Nullable<int> WILAYAT_ID { get; set; }
        public Nullable<int> VILLAGE_ID { get; set; }
        public Nullable<int> OTP_NUMBER { get; set; }
        public Nullable<bool> IS_OTP_VALIDATED { get; set; }
        public Nullable<bool> SMS_SENT_STATUS { get; set; }
        public Nullable<System.DateTime> LAST_LOGGED_IN_DATE { get; set; }
        public Nullable<bool> IS_TICKET_SUBMISSION_RESTRICTED { get; set; }
        public Nullable<int> TICKET_SUBMISSION_INTERVAL_DAYS { get; set; }
        public Nullable<int> NO_OF_TIMES_OTP_SEND { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<int> MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public Nullable<System.DateTime> LAST_TICKET_SUBMISSION_DATE { get; set; }
    
        public virtual USERS USERS { get; set; }
    }
}
