//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Takamul.Portal.Resources.Portal.News {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NewsResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NewsResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Takamul.Portal.Resources.Portal.News.NewsResx", typeof(NewsResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New News.
        /// </summary>
        public static string AddNewNews {
            get {
                return ResourceManager.GetString("AddNewNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add News.
        /// </summary>
        public static string AddNews {
            get {
                return ResourceManager.GetString("AddNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All News.
        /// </summary>
        public static string AllNews {
            get {
                return ResourceManager.GetString("AllNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only allowed file size upto 10 MB..
        /// </summary>
        public static string AllowedFileSize {
            get {
                return ResourceManager.GetString("AllowedFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        public static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete News.
        /// </summary>
        public static string DeleteNews {
            get {
                return ResourceManager.GetString("DeleteNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit News.
        /// </summary>
        public static string EditNews {
            get {
                return ResourceManager.GetString("EditNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded file is not a valid format.Only PNG,JPG,JPEG is allowed..
        /// </summary>
        public static string InvalidFileFormats {
            get {
                return ResourceManager.GetString("InvalidFileFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Notify User.
        /// </summary>
        public static string IsNotifyUser {
            get {
                return ResourceManager.GetString("IsNotifyUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Category.
        /// </summary>
        public static string NewsCategory {
            get {
                return ResourceManager.GetString("NewsCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Content.
        /// </summary>
        public static string NewsContent {
            get {
                return ResourceManager.GetString("NewsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Image.
        /// </summary>
        public static string NewsImage {
            get {
                return ResourceManager.GetString("NewsImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News List.
        /// </summary>
        public static string NewsList {
            get {
                return ResourceManager.GetString("NewsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Title.
        /// </summary>
        public static string NewsTitle {
            get {
                return ResourceManager.GetString("NewsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify User.
        /// </summary>
        public static string NotifyUser {
            get {
                return ResourceManager.GetString("NotifyUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select file to upload..
        /// </summary>
        public static string PleaseChooseFile {
            get {
                return ResourceManager.GetString("PleaseChooseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published Date.
        /// </summary>
        public static string PublishedDate {
            get {
                return ResourceManager.GetString("PublishedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search News.
        /// </summary>
        public static string SearchNews {
            get {
                return ResourceManager.GetString("SearchNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit News.
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded News Image.
        /// </summary>
        public static string UploadedNewsImage {
            get {
                return ResourceManager.GetString("UploadedNewsImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youtube Link.
        /// </summary>
        public static string YoutubeLink {
            get {
                return ResourceManager.GetString("YoutubeLink", resourceCulture);
            }
        }
    }
}
