//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Takamul.Portal.Resources.Portal.Tickets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TicketsResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TicketsResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Takamul.Portal.Resources.Portal.Tickets.TicketsResx", typeof(TicketsResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Ticket.
        /// </summary>
        public static string AddNewTicket {
            get {
                return ResourceManager.GetString("AddNewTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Ticket.
        /// </summary>
        public static string AddTicket {
            get {
                return ResourceManager.GetString("AddTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only allowed file size upto 10 MB..
        /// </summary>
        public static string AllowedFileSize {
            get {
                return ResourceManager.GetString("AllowedFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Participants.
        /// </summary>
        public static string AllTicketParticipants {
            get {
                return ResourceManager.GetString("AllTicketParticipants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Tickets.
        /// </summary>
        public static string AllTickets {
            get {
                return ResourceManager.GetString("AllTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Ticket Status.
        /// </summary>
        public static string ChangeTicketStatus {
            get {
                return ResourceManager.GetString("ChangeTicketStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose one participant..
        /// </summary>
        public static string ChooseOneParticipant {
            get {
                return ResourceManager.GetString("ChooseOneParticipant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        public static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Participant.
        /// </summary>
        public static string DeleteParticipant {
            get {
                return ResourceManager.GetString("DeleteParticipant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot delete ticket owner..
        /// </summary>
        public static string DeleteTicketOwnerUser {
            get {
                return ResourceManager.GetString("DeleteTicketOwnerUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enterreject reason&amp;hellip;&amp;hellip;.
        /// </summary>
        public static string EnterRejectReason {
            get {
                return ResourceManager.GetString("EnterRejectReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your message....
        /// </summary>
        public static string EnterYourMessage {
            get {
                return ResourceManager.GetString("EnterYourMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Back To Tickets.
        /// </summary>
        public static string GoBackToTickets {
            get {
                return ResourceManager.GetString("GoBackToTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To Chats.
        /// </summary>
        public static string GoToChats {
            get {
                return ResourceManager.GetString("GoToChats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has uploaded a file..
        /// </summary>
        public static string HasUploadedFile {
            get {
                return ResourceManager.GetString("HasUploadedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded file is not a valid format.Only PNG,JPG,JPEG is allowed..
        /// </summary>
        public static string InvalidFileFormat {
            get {
                return ResourceManager.GetString("InvalidFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant User.
        /// </summary>
        public static string ParticipantUser {
            get {
                return ResourceManager.GetString("ParticipantUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select file to upload..
        /// </summary>
        public static string PleaseSelectFile {
            get {
                return ResourceManager.GetString("PleaseSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reached maximum number of allowed users on this ticket..
        /// </summary>
        public static string ReachedLimitParticipantUser {
            get {
                return ResourceManager.GetString("ReachedLimitParticipantUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject Reason.
        /// </summary>
        public static string RejectReason {
            get {
                return ResourceManager.GetString("RejectReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Tickets.
        /// </summary>
        public static string SearchTickets {
            get {
                return ResourceManager.GetString("SearchTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Select Status -.
        /// </summary>
        public static string SelectStatus {
            get {
                return ResourceManager.GetString("SelectStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Select User -.
        /// </summary>
        public static string SelectUser {
            get {
                return ResourceManager.GetString("SelectUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon-circle-right2.
        /// </summary>
        public static string SendIcon {
            get {
                return ResourceManager.GetString("SendIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Chats.
        /// </summary>
        public static string TicketChats {
            get {
                return ResourceManager.GetString("TicketChats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Code.
        /// </summary>
        public static string TicketCode {
            get {
                return ResourceManager.GetString("TicketCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Platform.
        /// </summary>
        public static string TicketCreatedPlatform {
            get {
                return ResourceManager.GetString("TicketCreatedPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Descirption.
        /// </summary>
        public static string TicketDescirption {
            get {
                return ResourceManager.GetString("TicketDescirption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Description.
        /// </summary>
        public static string TicketDescription {
            get {
                return ResourceManager.GetString("TicketDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Details.
        /// </summary>
        public static string TicketDetails {
            get {
                return ResourceManager.GetString("TicketDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Image.
        /// </summary>
        public static string TicketImage {
            get {
                return ResourceManager.GetString("TicketImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Info.
        /// </summary>
        public static string TicketInfo {
            get {
                return ResourceManager.GetString("TicketInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Name.
        /// </summary>
        public static string TicketName {
            get {
                return ResourceManager.GetString("TicketName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Owner.
        /// </summary>
        public static string TicketOwnerUserFullName {
            get {
                return ResourceManager.GetString("TicketOwnerUserFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant Name.
        /// </summary>
        public static string TicketParticipantName {
            get {
                return ResourceManager.GetString("TicketParticipantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Participants .
        /// </summary>
        public static string TicketParticipantNos {
            get {
                return ResourceManager.GetString("TicketParticipantNos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Participant User.
        /// </summary>
        public static string TicketParticipantUser {
            get {
                return ResourceManager.GetString("TicketParticipantUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets List.
        /// </summary>
        public static string TicketsList {
            get {
                return ResourceManager.GetString("TicketsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Status.
        /// </summary>
        public static string TicketStatus {
            get {
                return ResourceManager.GetString("TicketStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Ticket.
        /// </summary>
        public static string UpdateTicket {
            get {
                return ResourceManager.GetString("UpdateTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded Ticket Image.
        /// </summary>
        public static string UploadedTicketImage {
            get {
                return ResourceManager.GetString("UploadedTicketImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UploadFile.
        /// </summary>
        public static string UploadFile {
            get {
                return ResourceManager.GetString("UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user already exists..
        /// </summary>
        public static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Ticket Info.
        /// </summary>
        public static string ViewTicketInfo {
            get {
                return ResourceManager.GetString("ViewTicketInfo", resourceCulture);
            }
        }
    }
}
