//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Takamul.Portal.Resources.Portal.ApplicationDashboard {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppDashboardResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppDashboardResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Takamul.Portal.Resources.Portal.ApplicationDashboard.AppDashboardResx", typeof(AppDashboardResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active tickets.
        /// </summary>
        public static string Activetickets {
            get {
                return ResourceManager.GetString("Activetickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App ID.
        /// </summary>
        public static string AppID {
            get {
                return ResourceManager.GetString("AppID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Name.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Summary.
        /// </summary>
        public static string ApplicationSummary {
            get {
                return ResourceManager.GetString("ApplicationSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed tickets.
        /// </summary>
        public static string Closedtickets {
            get {
                return ResourceManager.GetString("Closedtickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreatedDate.
        /// </summary>
        public static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due.
        /// </summary>
        public static string Due {
            get {
                return ResourceManager.GetString("Due", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exipry Date.
        /// </summary>
        public static string ExipryDate {
            get {
                return ResourceManager.GetString("ExipryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To Tickets.
        /// </summary>
        public static string GoToTickets {
            get {
                return ResourceManager.GetString("GoToTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Name.
        /// </summary>
        public static string MemberName {
            get {
                return ResourceManager.GetString("MemberName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mobile users.
        /// </summary>
        public static string MobileUsers {
            get {
                return ResourceManager.GetString("MobileUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Months.
        /// </summary>
        public static string Months {
            get {
                return ResourceManager.GetString("Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active tickets found..
        /// </summary>
        public static string NoActiveTicketFound {
            get {
                return ResourceManager.GetString("NoActiveTicketFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No closed tickets found..
        /// </summary>
        public static string NoClosedTicketsFound {
            get {
                return ResourceManager.GetString("NoClosedTicketsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No rejected tickets found..
        /// </summary>
        public static string NoRejectedTicketsFound {
            get {
                return ResourceManager.GetString("NoRejectedTicketsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Tickets.
        /// </summary>
        public static string OpenTickets {
            get {
                return ResourceManager.GetString("OpenTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply.
        /// </summary>
        public static string Reply {
            get {
                return ResourceManager.GetString("Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds.
        /// </summary>
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support tickets.
        /// </summary>
        public static string SupportTickets {
            get {
                return ResourceManager.GetString("SupportTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total closed tickets.
        /// </summary>
        public static string totalclosedtickets {
            get {
                return ResourceManager.GetString("totalclosedtickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total messages.
        /// </summary>
        public static string totalmessages {
            get {
                return ResourceManager.GetString("totalmessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total tickets.
        /// </summary>
        public static string TotalTickets {
            get {
                return ResourceManager.GetString("TotalTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Chats.
        /// </summary>
        public static string ViewChats {
            get {
                return ResourceManager.GetString("ViewChats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years.
        /// </summary>
        public static string Years {
            get {
                return ResourceManager.GetString("Years", resourceCulture);
            }
        }
    }
}
