//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Takamul.Portal.Resources.Portal.MemberInfo {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MemberInfoResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MemberInfoResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Takamul.Portal.Resources.Portal.MemberInfo.MemberInfoResx", typeof(MemberInfoResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Member Info.
        /// </summary>
        public static string AddMemberInfo {
            get {
                return ResourceManager.GetString("AddMemberInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Member.
        /// </summary>
        public static string AddNewMember {
            get {
                return ResourceManager.GetString("AddNewMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Member Info.
        /// </summary>
        public static string AddNewMemberInfo {
            get {
                return ResourceManager.GetString("AddNewMemberInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already added maximum number of list..
        /// </summary>
        public static string AlreadyAddedMaximumList {
            get {
                return ResourceManager.GetString("AlreadyAddedMaximumList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Member Info.
        /// </summary>
        public static string DeleteMemberInfo {
            get {
                return ResourceManager.GetString("DeleteMemberInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Member Info.
        /// </summary>
        public static string EditMemberInfo {
            get {
                return ResourceManager.GetString("EditMemberInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Info.
        /// </summary>
        public static string MemberInfo {
            get {
                return ResourceManager.GetString("MemberInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Info Description.
        /// </summary>
        public static string MemberInfoDescription {
            get {
                return ResourceManager.GetString("MemberInfoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Info Title.
        /// </summary>
        public static string MemberInfoTitle {
            get {
                return ResourceManager.GetString("MemberInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
