//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Takamul.Portal.Resources.Controls.GridView {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GridView {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GridView() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Takamul.Portal.Resources.Controls.GridView.GridView", typeof(GridView).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ltr.
        /// </summary>
        internal static string Direction {
            get {
                return ResourceManager.GetString("Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FloatingLeft {
            get {
                return ResourceManager.GetString("FloatingLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0px.
        /// </summary>
        internal static string FloatingRight {
            get {
                return ResourceManager.GetString("FloatingRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ui-icon ace-icon fa fa-angle-double-left bigger-140.
        /// </summary>
        internal static string MultiPagerArrowLeft {
            get {
                return ResourceManager.GetString("MultiPagerArrowLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ui-icon ace-icon fa fa-angle-double-right bigger-140.
        /// </summary>
        internal static string MultiPagerArrowRight {
            get {
                return ResourceManager.GetString("MultiPagerArrowRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ui-icon ace-icon fa fa-angle-left bigger-140.
        /// </summary>
        internal static string SinglePagerArrowLeft {
            get {
                return ResourceManager.GetString("SinglePagerArrowLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ui-icon ace-icon fa fa-angle-right bigger-140.
        /// </summary>
        internal static string SinglePagerArrowRight {
            get {
                return ResourceManager.GetString("SinglePagerArrowRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to right.
        /// </summary>
        internal static string TextAlign {
            get {
                return ResourceManager.GetString("TextAlign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left.
        /// </summary>
        internal static string TextDirection {
            get {
                return ResourceManager.GetString("TextDirection", resourceCulture);
            }
        }
    }
}
