USE [master]
GO

/****** Object:  Database [Takamul]    Script Date: 3/25/2017 5:39:29 PM ******/
DROP DATABASE [Takamul]
GO

/****** Object:  Database [Takamul]    Script Date: 3/25/2017 5:39:29 PM ******/
CREATE DATABASE [Takamul]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Takamul', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER2014\MSSQL\DATA\Takamul.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Takamul_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER2014\MSSQL\DATA\Takamul_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Takamul] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Takamul].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Takamul] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Takamul] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Takamul] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Takamul] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Takamul] SET ARITHABORT OFF 
GO

ALTER DATABASE [Takamul] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Takamul] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Takamul] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Takamul] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Takamul] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Takamul] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Takamul] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Takamul] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Takamul] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Takamul] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Takamul] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Takamul] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Takamul] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Takamul] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Takamul] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Takamul] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Takamul] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Takamul] SET RECOVERY FULL 
GO

ALTER DATABASE [Takamul] SET  MULTI_USER 
GO

ALTER DATABASE [Takamul] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Takamul] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Takamul] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Takamul] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Takamul] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Takamul] SET  READ_WRITE 
GO


